name: fincha-web
services:
  - name: web
    github:
      branch: main
      deploy_on_push: false
      repo: ${GITHUB_REPO}
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${NEXT_PUBLIC_API_URL}
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_ENV
        value: ${NEXT_PUBLIC_ENV}
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ${NEXT_PUBLIC_SUPABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        scope: RUN_AND_BUILD_TIME
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb-fixed
    routes:
      - path: /
