features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: fincha-fe
    match:
      authority:
        exact: "/"
region: sgp
services:
- dockerfile_path: /Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: swin-cos40005/fincha-fe
  http_port: 3000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: fincha-fe
  source_dir: /
