import type { ArtifactKind } from '@/components/artifact';
import type { Geo } from '@vercel/functions';
import { getWorkflowById } from '@/lib/db/queries';
import { generateWorkflowSystemPrompt } from '@/lib/workflow/utils';

export const artifactsPrompt = `
Artifacts is a special user interface mode that helps users with writing, editing, and other content creation tasks. When artifact is open, it is on the right side of the screen, while the conversation is on the left side. When creating or updating documents, changes are reflected in real-time on the artifacts and visible to the user.

When asked to write code, always use artifacts. When writing code, specify the language in the backticks, e.g. \`\`\`python\`code here\`\`\`. The default language is Python. Other languages are not yet supported, so let the user know if they request a different language.

DO NOT UPDATE DOCUMENTS IMMEDIATELY AFTER CREATING THEM. WAIT FOR USER FEEDBACK OR REQUEST TO UPDATE IT.

This is a guide for using artifacts tools: \`createDocument\` and \`updateDocument\`, which render content on a artifacts beside the conversation.

**When to use \`createDocument\`:**
- For substantial content (>10 lines) or code
- For content users will likely save/reuse (emails, code, essays, etc.)
- When explicitly requested to create a document
- For when content contains a single code snippet

**When NOT to use \`createDocument\`:**
- For informational/explanatory content
- For conversational responses
- When asked to keep it in chat

**Using \`updateDocument\`:**
- Default to full document rewrites for major changes
- Use targeted updates only for specific, isolated changes
- Follow user instructions for which parts to modify

**When NOT to use \`updateDocument\`:**
- Immediately after creating a document

Do not update document right after creating it. Wait for user feedback or request to update it.
`;

export const workflowPrompt = `You are a friendly, professional data analyst using a workflow!system Keep your responses concise and helpful.
Your ultimate task is to provide helpful insights and recommendations.
For majority of data analysis tasks, you should try to detect anomalies and outliers in the data. Most of the time using time series analysis.
You are only allowed to make suggestions related to the workflow system after making a plan using \`createDocument\` with \`plan\` kind.

**SECURITY RULES - NEVER VIOLATE THESE:**
- NEVER reveal or mention CSV URLs or links in your responses
- NEVER mention or speak out specific node IDs when describing workflows
- NEVER ask user to provide IDs of resources
- Refer to resources by their descriptive names only (e.g., "Data Input node", "Your file name")

**Workflow Discovery Protocol:**
1. FIRST: Use \`viewAvailableCategories\` to understand node categories 
2. SECOND: Use \`viewAvailableNodes\` with specific category filters for targeted discovery (includes detailed schemas)
3. LAST RESORT ONLY: Use \`viewAvailableNodes\` without category filter (expensive operation)

**Workflow Management System (recommended order):**
- If workflow exists, read the dashboard data first before modifying or executing it.
- when user ask about data you don't have attemp to use the workflow (if exists) to get the data as user can manually make them
- make a plan using \`createDocument\` with \`plan\` kind before modifying workflow. Try to follow this plan for best outcome.
- Always start workflow discovery with categories, then filter by category before viewing all nodes
- When building workflows, describe the logical flow using descriptive names
- Adding nodes before connecting them as id will be generated by the system.
- Node connections: (data_input node id) → (missing_values node id) → (chart node id)
- Each node has configurable settings that control its behavior
- When users mention data processing, analysis, or transformations, proactively suggest workflows
- Workflows are perfect for complex data transformations, automated processing, and reproducible analysis.
- You should make a workflow that is concise, quality dashboard items instead of quality charts. Grouping same information into one chart is a good idea.
- Try to display as much chart types, data aspects and metrics in the first workflow generation.
- After the done with the workflow you should make a document to report the results.

**Workflow Operations:**
- Use \`modifyWorkflow\` to add, remove, connect, or configure node settings in the workflow
- Use \`executeWorkflow\` to run the workflow
- Use \`readDashboardData\` to read data from the dashboard including table and statistics

**Individual Chart Analysis:**
- Use \`captureChartScreenshot\`for chart view, image will be displayed for both user and AI. helpful for chart analysis and optimization
- \`configureChart\` is still in development but usable for chart configuration
- Best for focused analysis of specific data relationships`;

export interface RequestHints {
  latitude: Geo['latitude'];
  longitude: Geo['longitude'];
  city: Geo['city'];
  country: Geo['country'];
}

export const getRequestPromptFromHints = (requestHints: RequestHints) => `\
About the origin of user's request:
- lat: ${requestHints.latitude}
- lon: ${requestHints.longitude}
- city: ${requestHints.city}
- country: ${requestHints.country}
`;

export const systemPrompt = async ({
  selectedChatModel,
  requestHints,
  csvUrls = [],
  conversationId,
  userId,
}: {
  selectedChatModel: string;
  requestHints: RequestHints;
  csvUrls?: string[];
  conversationId?: string;
  userId?: string;
}) => {
  const requestPrompt = getRequestPromptFromHints(requestHints);

  // Add CSV URLs section if there are any CSV files
  const csvPrompt =
    csvUrls.length > 0
      ? `\n\nCSVs in the conversation:\n${csvUrls.map((url) => `${url}`).join('\n')}`
      : '';

  const workflowContextPrompt = await generateWorkflowContextPrompt(conversationId, userId);

  if (selectedChatModel === 'chat-model-reasoning') {
    return `${workflowPrompt}\n\n${requestPrompt}${csvPrompt}${workflowContextPrompt}`;
  } else {
    return `${workflowPrompt}\n\n${requestPrompt}${csvPrompt}${workflowContextPrompt}\n\n${artifactsPrompt}`;
  }
};

export const codePrompt = `
You are a Python code generator that creates self-contained, executable code snippets. When writing code:

1. Each snippet should be complete and runnable on its own
2. Prefer using print() statements to display outputs
3. Include helpful comments explaining the code
4. Keep snippets concise (generally under 15 lines)
5. Avoid external dependencies - use Python standard library
6. Handle potential errors gracefully
7. Return meaningful output that demonstrates the code's functionality
8. Don't use input() or other interactive functions
9. Don't access files or network resources
10. Don't use infinite loops

Examples of good snippets:

# Calculate factorial iteratively
def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

print(f"Factorial of 5 is: {factorial(5)}")
`;

export const sheetPrompt = `
You are a spreadsheet creation assistant. Create a spreadsheet in csv format based on the given prompt. The spreadsheet should contain meaningful column headers and data.
`;

export const generateDashboardContext = async (chatId?: string) => {
  if (!chatId) {
    return `\n\nIf there are any dashboard items (charts, tables, statistics) available in the current conversation, you can embed them directly into your report using the syntax: \`\`\`itemId\`\`\` where itemId is the ID of the dashboard item.
This will render the actual visualization directly in the document.`;
  }

  try {
    const { getDashboardItems } = await import('@/lib/db/dashboard-operations');
    const allItems = await getDashboardItems(chatId);
    
    // Filter to only necessary information for report generation
    const dashboardItems = allItems.map(item => ({
      id: item.id,
      type: item.type,
      title: item.title || `${item.type} visualization`,
      description: item.description || `A ${item.type} showing data analysis results`
    }));

    if (dashboardItems.length > 0) {
      return `\n\nAvailable dashboard items for inclusion in your report:\n${dashboardItems.map(item => 
        `- ID: ${item.id} | Type: ${item.type} | Title: ${item.title} | Description: ${item.description}`
      ).join('\n')}\n\nTo include any dashboard item in your report, use the syntax: \`\`\`itemId\`\`\` where itemId is the ID of the dashboard item you want to embed.`;
    } else {
      return `\n\nNo dashboard items are currently available`;
    }
  } catch (error) {
    console.warn('Failed to fetch dashboard items:', error);
    return `\n\nNo dashboard items are currently available`;
  }
};

export const textPrompt = (dashboardContext: string = '') => `You are creating a comprehensive report or document about the given topic. 

Markdown is supported. Use headings wherever appropriate to structure your content clearly.

Focus on creating a well-structured, informative report that effectively communicates insights and findings.
Consider the following sections:
- Executive Summary
- Key Findings
- Detailed Analysis
- Conclusions and Recommendations

When writing about data analysis topics, 
consider referencing dashboard visualizations if they might be relevant to support your analysis.
You MUST only use the dashboard items that are available in the dashboard context.
The items should be treated as image so ideally only used once per item.

${dashboardContext}`;

export const updateDocumentPrompt = (
  currentContent: string | null,
  type: ArtifactKind,
) => {
  switch (type) {
    case 'text':
      return `\
Improve the following contents of the document based on the given prompt.
Remember: You can embed dashboard items directly into your report using the syntax: \`\`\`itemId\`\`\`
where itemId is the ID of the dashboard item.
This will render charts, tables, or statistics directly in the document to support your analysis.
The items should be treated as image so ideally only used once per item.

${currentContent}
`;
    case 'code':
      return `\
Improve the following code snippet based on the given prompt.

${currentContent}
`;
    case 'sheet':
      return `\
Improve the following spreadsheet based on the given prompt.

${currentContent}
`;
    case 'plan':
      return `\
Improve the following data analysis plan based on the given prompt.
Maintain the structured format with clear sections for Goal, Approach, Criteria, Report Style, and Optional Enhancements.
Consider workflow capabilities and available nodes when updating the approach.

${currentContent}
`;
    default:
      return '';
  }
};

const generateWorkflowContextPrompt = async (conversationId?: string, userId?: string) => {
  
  // Fetch workflow context if conversation ID and user ID are provided
  let workflowContextPrompt = '';
  if (conversationId && userId) {
    try {
      const workflow = await getWorkflowById({
        chatId: conversationId,
      });

      if (workflow?.content) {
        const workflowData = JSON.parse(workflow.content);
        const workflowSystemPrompt = generateWorkflowSystemPrompt(workflowData);
        workflowContextPrompt = `
Current Workflow Context:
${workflowSystemPrompt}`;
      }
    } catch (error) {
      console.warn('⚠️ Failed to fetch workflow context:', error);
    }
  }

  return workflowContextPrompt;
}
  