name: Automatically create / update pull request

on:
  push:
    branches-ignore:
      - "main"
      - "dependabot/**"

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Format branch name as title
        id: branch
        run: |
          BRANCH="${{ github.ref_name }}"
          TITLE=$(echo "$BRANCH" | sed 's/[\/\-_]/ /g' | sed 's/ *#[0-9]*$//')
          echo "title=$TITLE" >> $GITHUB_OUTPUT

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "${{ steps.branch.outputs.title }}"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_draft: true
